# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\",\n\x0eSetRoleRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0c\n\x04role\x18\x02 \x01(\t\"1\n\x0fSetRoleResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08\x12\x0e\n\x06status\x18\x02 \x01(\t26\n\x04\x41uth\x12.\n\x07SetRole\x12\x0f.SetRoleRequest\x1a\x10.SetRoleResponse\"\x00\x62\x06proto3')



_SETROLEREQUEST = DESCRIPTOR.message_types_by_name['SetRoleRequest']
_SETROLERESPONSE = DESCRIPTOR.message_types_by_name['SetRoleResponse']
SetRoleRequest = _reflection.GeneratedProtocolMessageType('SetRoleRequest', (_message.Message,), {
  'DESCRIPTOR' : _SETROLEREQUEST,
  '__module__' : 'auth_pb2'
  # @@protoc_insertion_point(class_scope:SetRoleRequest)
  })
_sym_db.RegisterMessage(SetRoleRequest)

SetRoleResponse = _reflection.GeneratedProtocolMessageType('SetRoleResponse', (_message.Message,), {
  'DESCRIPTOR' : _SETROLERESPONSE,
  '__module__' : 'auth_pb2'
  # @@protoc_insertion_point(class_scope:SetRoleResponse)
  })
_sym_db.RegisterMessage(SetRoleResponse)

_AUTH = DESCRIPTOR.services_by_name['Auth']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SETROLEREQUEST._serialized_start=14
  _SETROLEREQUEST._serialized_end=58
  _SETROLERESPONSE._serialized_start=60
  _SETROLERESPONSE._serialized_end=109
  _AUTH._serialized_start=111
  _AUTH._serialized_end=165
# @@protoc_insertion_point(module_scope)
