# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth_grpc/auth.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61uth_grpc/auth.proto\",\n\x0eSetRoleRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0c\n\x04role\x18\x02 \x01(\t\"1\n\x0fSetRoleResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08\x12\x0e\n\x06status\x18\x02 \x01(\t\"&\n\x16\x43heckUserExistsRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\")\n\x17\x43heckUserExistsResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08\x32~\n\x04\x41uth\x12.\n\x07SetRole\x12\x0f.SetRoleRequest\x1a\x10.SetRoleResponse\"\x00\x12\x46\n\x0f\x43heckUserExists\x12\x17.CheckUserExistsRequest\x1a\x18.CheckUserExistsResponse\"\x00\x62\x06proto3')



_SETROLEREQUEST = DESCRIPTOR.message_types_by_name['SetRoleRequest']
_SETROLERESPONSE = DESCRIPTOR.message_types_by_name['SetRoleResponse']
_CHECKUSEREXISTSREQUEST = DESCRIPTOR.message_types_by_name['CheckUserExistsRequest']
_CHECKUSEREXISTSRESPONSE = DESCRIPTOR.message_types_by_name['CheckUserExistsResponse']
SetRoleRequest = _reflection.GeneratedProtocolMessageType('SetRoleRequest', (_message.Message,), {
  'DESCRIPTOR' : _SETROLEREQUEST,
  '__module__' : 'auth_grpc.auth_pb2'
  # @@protoc_insertion_point(class_scope:SetRoleRequest)
  })
_sym_db.RegisterMessage(SetRoleRequest)

SetRoleResponse = _reflection.GeneratedProtocolMessageType('SetRoleResponse', (_message.Message,), {
  'DESCRIPTOR' : _SETROLERESPONSE,
  '__module__' : 'auth_grpc.auth_pb2'
  # @@protoc_insertion_point(class_scope:SetRoleResponse)
  })
_sym_db.RegisterMessage(SetRoleResponse)

CheckUserExistsRequest = _reflection.GeneratedProtocolMessageType('CheckUserExistsRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHECKUSEREXISTSREQUEST,
  '__module__' : 'auth_grpc.auth_pb2'
  # @@protoc_insertion_point(class_scope:CheckUserExistsRequest)
  })
_sym_db.RegisterMessage(CheckUserExistsRequest)

CheckUserExistsResponse = _reflection.GeneratedProtocolMessageType('CheckUserExistsResponse', (_message.Message,), {
  'DESCRIPTOR' : _CHECKUSEREXISTSRESPONSE,
  '__module__' : 'auth_grpc.auth_pb2'
  # @@protoc_insertion_point(class_scope:CheckUserExistsResponse)
  })
_sym_db.RegisterMessage(CheckUserExistsResponse)

_AUTH = DESCRIPTOR.services_by_name['Auth']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SETROLEREQUEST._serialized_start=24
  _SETROLEREQUEST._serialized_end=68
  _SETROLERESPONSE._serialized_start=70
  _SETROLERESPONSE._serialized_end=119
  _CHECKUSEREXISTSREQUEST._serialized_start=121
  _CHECKUSEREXISTSREQUEST._serialized_end=159
  _CHECKUSEREXISTSRESPONSE._serialized_start=161
  _CHECKUSEREXISTSRESPONSE._serialized_end=202
  _AUTH._serialized_start=204
  _AUTH._serialized_end=330
# @@protoc_insertion_point(module_scope)
