# Generated by Django 4.0.2 on 2022-02-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribtions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='period',
            field=models.TextField(choices=[('Week', 'Week'), ('Month', 'Month'), ('Year', 'Year')], default='Month', verbose_name='Период подписки'),
        ),
    ]
