# Generated by Django 4.0.2 on 2022-02-20 17:53

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribtions', '0002_alter_tariff_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата + время создания'),
        ),
        migrations.AlterField(
            model_name='account',
            name='payment_token',
            field=models.TextField(blank=True, null=True, unique=True, verbose_name='Платежный токен'),
        ),
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.TextField(choices=[('Active', 'Active'), ('Overdue', 'Overdue'), ('Canceled', 'Canceled')], db_index=True, verbose_name='Статус подписки'),
        ),
        migrations.AlterField(
            model_name='account',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата + время обновления'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата + время создания'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата + время обновления'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата + время создания'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='period',
            field=models.DurationField(choices=[(datetime.timedelta(days=7), 'Week'), (datetime.timedelta(days=28), 'Month'), (datetime.timedelta(days=364), 'Year')], default=datetime.timedelta(days=28), verbose_name='Период подписки'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата + время обновления'),
        ),
    ]
