# Generated by Django 4.0.2 on 2022-02-20 18:16

import datetime
import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribtions', '0003_alter_account_created_at_alter_account_payment_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='account',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='subscribtions.account'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='amount',
            field=models.PositiveIntegerField(blank=True, editable=False, verbose_name='Сумма к оплате'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='due_dt',
            field=models.DateField(blank=True, editable=False, verbose_name='Срок оплаты'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='paid_period',
            field=models.DurationField(blank=True, editable=False, verbose_name='Оплачиваемый период'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='period',
            field=models.DurationField(choices=[(datetime.timedelta(days=7), 'Week'), (datetime.timedelta(days=28), 'Month'), (datetime.timedelta(days=364), 'Year')], default=datetime.timedelta(days=28), verbose_name='Период подписки'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата + время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата + время обновления')),
                ('is_success', models.BooleanField(blank=True, default=False, verbose_name='Статус оплаты')),
                ('bill', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='subscribtions.bill')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
