# Generated by Django 4.0.2 on 2022-02-20 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribtions', '0004_alter_bill_account_alter_bill_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='due_dt',
        ),
        migrations.AlterField(
            model_name='tariff',
            name='period',
            field=models.DurationField(choices=[(datetime.timedelta(days=7), 'Week'), (datetime.timedelta(days=28), 'Month'), (datetime.timedelta(days=364), 'Year')], default=datetime.timedelta(days=28), verbose_name='Период подписки'),
        ),
    ]
