# Generated by Django 4.0.2 on 2022-02-20 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribtions', '0005_remove_bill_due_dt_alter_tariff_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='period',
            field=models.DurationField(choices=[(datetime.timedelta(days=7), 'Week'), (datetime.timedelta(days=30), 'Month'), (datetime.timedelta(days=356), 'Year')], default=datetime.timedelta(days=30), verbose_name='Период подписки'),
        ),
    ]
