# Generated by Django 4.0.2 on 2022-03-01 20:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribtions', '0009_bill_paid_period_alter_tariff_period'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Аккаунт', 'verbose_name_plural': 'Аккаунты'},
        ),
        migrations.AlterModelOptions(
            name='bill',
            options={'verbose_name': 'Счет', 'verbose_name_plural': 'Счета'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Транзакция', 'verbose_name_plural': 'Транзакции'},
        ),
        migrations.AlterModelOptions(
            name='tariff',
            options={'verbose_name': 'Тариф', 'verbose_name_plural': 'Тарифы'},
        ),
        migrations.AddField(
            model_name='bill',
            name='card_cryptogram_packet',
            field=models.TextField(blank=True, null=True, verbose_name='Криптограмма'),
        ),
        migrations.AddField(
            model_name='bill',
            name='ip_address',
            field=models.TextField(blank=True, null=True, verbose_name='IP адрес'),
        ),
        migrations.AddField(
            model_name='bill',
            name='pa_res',
            field=models.TextField(blank=True, null=True, verbose_name='Pa Res'),
        ),
        migrations.AddField(
            model_name='bill',
            name='payment_type',
            field=models.TextField(blank=True, choices=[('Cryptogram', 'Cryptogram'), ('Token', 'Token'), ('3DS', 'Post3Ds')], verbose_name='Тип платежа'),
        ),
        migrations.AddField(
            model_name='payment',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='Информация'),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID транзакции'),
        ),
        migrations.AlterField(
            model_name='account',
            name='expiration_dt',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.TextField(choices=[('Active', 'Active'), ('Overdue', 'Overdue'), ('Canceled', 'Canceled')], db_index=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.TextField(choices=[('Paid', 'Paid'), ('In work', 'In Work'), ('Not paid', 'Not Paid')], default='In work', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='is_success',
            field=models.BooleanField(blank=True, default=False, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='amount',
            field=models.PositiveIntegerField(blank=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='period',
            field=models.DurationField(choices=[(datetime.timedelta(days=7), 'Week'), (datetime.timedelta(days=30), 'Month'), (datetime.timedelta(days=356), 'Year')], default=datetime.timedelta(days=30), verbose_name='Период'),
        ),
    ]
