# Generated by Django 4.0.2 on 2022-03-01 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribtions', '0010_alter_account_options_alter_bill_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='card_cryptogram_packet',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='Криптограмма'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='ip_address',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='IP адрес'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='pa_res',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='Pa Res'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='payment_type',
            field=models.TextField(blank=True, choices=[('Cryptogram', 'Cryptogram'), ('Token', 'Token'), ('3DS', 'Post3Ds')], editable=False, verbose_name='Тип платежа'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='ID транзакции'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='period',
            field=models.DurationField(choices=[(datetime.timedelta(days=7), 'Week'), (datetime.timedelta(days=30), 'Month'), (datetime.timedelta(days=356), 'Year')], default=datetime.timedelta(days=30), verbose_name='Период'),
        ),
    ]
